apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: node-1-ippool
spec:
  cidr: 192.168.30.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: rack == "rack1"

---

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: node-2-ippool
spec:
  cidr: 192.168.40.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: rack == "rack2"